version: '3.1'

services:
  php:
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
        - 80:80
      volumes:
        - ./src:/var/www/html/
  # Läs mer här: https://hub.docker.com/_/mysql
  # Använd inte som production-configuration
  db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # Username: root
    # Password: example
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  mysql-data: